.TH CRAS 1 cras\-VERSION
.SH NAME
.PP
cras - The Anti-Procrastination Tool
.SH SYNOPSIS
.PP
.B cras
.RB [ \-ailnoOv ]
.RB [ \-detT 
.IR num  ]
.I file
.SH DESCRIPTION
.PP
cras is an unapologetic daily task planner and manager for your terminal and WM
status bar. It holds your tasks only for a limited amount of time (24 hours, by
default).
.SH OPTIONS
.TP
.B \-a
Append new tasks to
.I file.
(Be aware that this doesn't update the expiration date.)
.TP
.BI \-d " num"
Delete task
.I
num.
.TP
.BI \-e " num"
Edit task
.I
num.
.TP
.B \-i
Force expiration of
.I file.
.TP
.B \-l
Only print the list of tasks.
.TP
.B \-n
Create new
.I file,
overwriting previous contents if it already exists.
.TP
.B \-o
Only print the counter of tasks pending and done.
.TP
.B \-O
Only print counter+description.
.TP
.BI \-t " num"
Mark task 
.I num 
as done.
.TP
.BI \-T " num"
Mark task
.I num 
as pending.
.TP
.B \-v
Show version information and exit.
.SH USAGE
.PP
To set up a new task list, call cras using the -n option. cras will read each 
new line from standard input as a new task, until EOF is reached. Add new tasks
to an already existing file using -a.
.PP
The newly created task list will be readable by cras only up to the expiry
date, which under the default configuration is 24 hours after originally saving
it. Use -t to mark a task as done and -T to mark it back as pending.
.PP
You may delete tasks by using the -d option followed by its identifying number.
You may similarly edit the description of a task by using the -e option. If you
want to set the whole file as already expired, you may do so by using the -i 
option.
.PP
Running cras with no options outputs the task list. For just a counter of 
tasks pending and done, pass the -o flag to cras. The -O flag extends the 
counter with the description shown in the default output mode. These two modes
are especially suited for integrating cras into scripts or WM status bars.
Using -l will print only the list of tasks.
.SH ENVIRONMENT VARIABLES
.PP
Execution of cras is affected by the following environment variables:
.TP
.B NO_COLOR
Setting it to any value disables ANSI color escapes on output.
.SH CONFIGURATION
.PP
cras is configured by creating a custom config.h and recompiling the source 
code.
.SH BUGS
.PP
Report bugs to https://todo.sr.ht/~arivigo/cras
