.TH CRAS 1 cras\-VERSION
.SH NAME
.PP
cras \- The Anti-Procrastination Tool
.SH SYNOPSIS
.PP
.B cras
.RB [ \-ailnoOv ]
.RB [ \-detT 
.IR num  ]
.RB [ file ]
.SH DESCRIPTION
.PP
.B cras 
is an unapologetic daily task list. 
It holds your tasks only throughout the day, 
deleting them afterwards.
.PP
To set up a new task list, call 
.B cras 
using the 
.I \-n 
option. 
.B cras 
will read each new line from standard input as a new task, 
until EOF is reached. 
Add new tasks to an already existing file using 
.IR \-a .
.PP
The newly created task list will be readable by 
.B cras 
only throughout the day saved on the list.
Use 
.I \-t 
to mark a task as done and 
.I \-T 
to mark it back as pending.
.PP
You may delete tasks by using the 
.I \-d 
option followed by its identifying number.
You may similarly edit the description of a task by using the 
.I \-e 
option. 
If you want to set the whole file as already expired,
you may do so by using the 
.I \-i 
option.
.PP
Running 
.B cras 
with no options outputs the task list. 
For just a counter of tasks pending and done, 
pass the 
.I \-o 
option to 
.BR cras . 
The 
.I \-O 
option extends the counter with the description shown in the default output 
mode. 
These two modes are especially suited for integrating 
.B cras 
into scripts or WM status bars. 
Using
.I \-l 
will print only the list of tasks.
.SH OPTIONS
.TP
.B \-a
Append new tasks to
.IR file .
.TP
.BI \-d " num"
Delete task
.IR num .
.TP
.BI \-e " num"
Edit task
.IR num .
.TP
.B \-i
Force expiration of
.IR file .
.TP
.B \-l
Only print the list of tasks.
.TP
.B \-n
Create new
.IR file ,
overwriting previous contents if it already exists.
.TP
.B \-o
Only print the counter of tasks pending and done.
.TP
.B \-O
Only print counter+description.
.TP
.BI \-t " num"
Mark task 
.I num 
as done.
.TP
.BI \-T " num"
Mark task
.I num 
as pending.
.TP
.B \-v
Show version information and exit.
.SH ENVIRONMENT
.PP
Execution of 
.B cras 
is affected by the following environment variables:
.TP
.B CRAS_DEF_FILE
Sets a default file location that 
.B cras 
opens if run without a
.I file
argument. 
.TP
.B NO_COLOR
Setting it to any value disables ANSI color escapes on output.
.SH EXAMPLES
.SS Task list operations
.PP
To set a task list up:
.PP
.nf
.RS
.RB $ " cras -n my-todo"
.br
.B "This is a test"
.br
.B "Writing a manpage"
.br
.B "For cras"
.RE
.fi
.PP
Checking a task list file:
.PP
.nf
.RS
.RB $ " cras my-todo"
.br
2021-03-22
.sp 2
#01 [TODO] This is a test
.br
#02 [TODO] Writing my manpage
.br
#03 [TODO] For cras
.sp 2
3/0 to do/done
.RE
.fi
.PP
Appending new entries:
.PP
.nf
.RS
.RB $ " cras -a my-todo"
.br
.B "New entry"
.br
.RB $ " cras my-todo"
.br
2021-03-22
.sp 2
#01 [TODO] This is a test
.br
#02 [TODO] Writing my manpage
.br
#03 [TODO] For cras
.br
#04 [TODO] New entry
.sp 2
4/0 to do/done
.RE
.fi
.PP
To force a task list to expire:
.PP
.nf
.RS
.RB $ " cras -i my-todo"
.RE
.fi
.SS Manipulating entries
.PP
Editing and deleting individual tasks:
.PP
.nf
.RS
.RB $ " cras -e 1 my-todo"
.br
.B "New text for entry 1"
.br
.RB $ " cras -d 2 my-todo"
.RE
.fi
.PP
To mark a task as done or back to not done, respectively:
.PP
.nf
.RS
.RB $ " cras -t 1 my-todo"
.br
#01 [DONE] Rewrite cras manpage
.br
.RB $ " cras -T 1 my-todo"
#01 [TODO] Rewrite cras manpage
.RE
.fi
.SH SEE ALSO
None.
